# Generated by Django 4.1.6 on 2023-02-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbtitle',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
