# Generated by Django 4.1.6 on 2023-02-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_imdbtitle_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbtitle',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='imdbtitle',
            name='release_year',
            field=models.IntegerField(default=1999),
            preserve_default=False,
        ),
    ]
