# Generated by Django 4.1.6 on 2023-02-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_imdbtitle_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbtitle',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
