# Generated by Django 4.1.6 on 2023-02-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_imdbtitle_rating_alter_imdbtitle_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImdbRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IMDbTitle',
        ),
    ]
