# Generated by Django 4.1.6 on 2023-04-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_titlegridsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleGridSettings',
            new_name='TitleGridSetting',
        ),
    ]
