# Generated by Django 4.1.6 on 2023-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_rename_titlegridsettings_titlegridsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlegridsetting',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
