# Generated by Django 4.1.6 on 2023-04-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_rename_titlegridsettings_titlegridsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImdbRating',
        ),
    ]
