# Generated by Django 4.1.4 on 2023-04-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_titlegridsetting_value'),
        ('mysite', '0012_delete_imdbrating'),
    ]

    operations = [
    ]
